# Practicing queries: Deliverable 3

## SQLite installation

In [2]:
import sqlite3

## Mount Drive and set path
n the left-hand side menu, we select the folder, then click on the "drive" folder and follow the corresponding steps.

Afterward, we look for our folder and copy the path of the one containing all the files we are working on, and include that path as the DRIVE_PATH variable.

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## Importing pandas library

In [5]:
import pandas as pd

## Importing the database

In [6]:
con = sqlite3.connect("/content/drive/MyDrive/eada material/classic.db")

## All the questions are related to the classicmodels database

1. List the name and vendor of those products that have not been included in any order.

In [ ]:
q="""
SELECT productCode, productName, productVendor
FROM products
WHERE productCode NOT IN (SELECT productCode FROM orderdetails)
"""
pd.read_sql(q,con)

  productCode        productName             productVendor
0    S18_3233  1985 Toyota Supra  Highway 66 Mini Classics

2. Create a field that categorizes the quantity of units ordered per order: less than 100, between 100 and 200, or more than 200. If an order has no order lines, it will be labeled as 'No order lines' in this field. How many orders are there of each type?

In [ ]:
q="""
WITH aux AS (
  SELECT SUM(od.quantityOrdered) AS tot_units, o.orderNumber,
  CASE WHEN SUM(od.quantityOrdered)<100 THEN "Less than 100"
  WHEN SUM(od.quantityOrdered) BETWEEN 100 AND 200 THEN "Between 100 and 200"
  WHEN SUM(od.quantityOrdered)>200 THEN "More than 200"
  ELSE "No order lines"
  END AS category
  FROM orders o
  LEFT JOIN orderdetails od ON o.orderNumber=od.OrderNumber
  GROUP BY o.orderNumber
)

SELECT COUNT(orderNumber)AS order_count, category
FROM aux
GROUP BY category"""
pd.read_sql(q,con)

   order_count             category
0           46  Between 100 and 200
1           43        Less than 100
2          237        More than 200

In [ ]:
q = """
WITH aux AS (
SELECT o.orderNumber, SUM(od.quantityOrdered) AS total_units,
CASE WHEN SUM(od.quantityOrdered) < 100 THEN 'Less than 100'
WHEN SUM(od.quantityOrdered) BETWEEN 100 AND 200 THEN 'Between 100 and 200'
WHEN SUM(od.quantityOrdered) > 200 THEN 'More than 200'
ELSE 'No order lines'
END AS category
  FROM orders o
  LEFT JOIN orderdetails od ON o.orderNumber = od.orderNumber
  GROUP BY o.orderNumber
)

SELECT COUNT(orderNumber) AS order_count, category
FROM aux
GROUP BY  category;
"""

pd.read_sql(q, con)

   order_count             category
0           46  Between 100 and 200
1           43        Less than 100
2          237        More than 200

3. Create a list of all postal codes where packages can be received or sent. In the case of an office, the 'Action' field will contain 'E', and in the case of a customer's address, it will contain 'R'. The list must not contain duplicates.

In [ ]:
q = """
SELECT postalCode, 'R' AS Action
FROM customers
UNION
SELECT postalCode, 'E' AS Action
FROM offices
"""

pd.read_sql(q, con)

    postalCode Action
0         0028      R
1       01-012      R
2        01307      R
3        02107      E
4       038988      R
..         ...    ...
97     T2F 8M4      R
98     V3F 2K1      R
99     WA1 1DP      R
100    WX1 6LT      R
101    WX3 6FW      R

[102 rows x 2 columns]

4. List all the products purchased by Herkku Gifts.

In [ ]:
q="""
SELECT p.productCode, p.productName
FROM products p
JOIN orderdetails od ON p.productCode=od.productCode
JOIN orders o ON od.orderNumber=o.orderNumber
JOIN customers c ON o.customerNumber=c.customerNumber
WHERE customerName="Herkku Gifts"
"""
pd.read_sql(q,con)

   productCode                                productName
0     S12_1099                          1968 Ford Mustang
1     S12_3380                         1968 Dodge Charger
2     S12_3990                    1970 Plymouth Hemi Cuda
3     S12_4675                         1969 Dodge Charger
4     S18_1129                            1993 Mazda RX-7
5     S18_1589                      1965 Aston Martin DB5
6     S18_1889                1948 Porsche 356-A Roadster
7     S18_1984                           1995 Honda Civic
8     S18_2870               1999 Indy 500 Monte Carlo SS
9     S18_3232                1992 Ferrari 360 Spider red
10    S18_3278                       1969 Dodge Super Bee
11    S18_3482                      1976 Ford Gran Torino
12    S18_3685             1948 Porsche Type 356 Roadster
13    S24_1628                  1966 Shelby Cobra 427 S/C
14    S24_2972                    1982 Lamborghini Diablo
15    S24_3371                  1971 Alpine Renault 1600s
16    S24_3856                    1956 Porsche 356A Coupe
17    S10_1678      1969 Harley Davidson Ultimate Chopper
18    S10_2016                      1996 Moto Guzzi 1100i
19    S10_4698       2003 Harley-Davidson Eagle Drag Bike
20    S18_2625        1936 Harley Davidson El Knucklehead
21    S24_1578                          1997 BMW R 1100 S
22    S24_2000                   1960 BSA Gold Star DBD34
23    S32_1374                           1997 BMW F650 ST
24   S700_2834                              ATA: B757-300
25    S18_1342                       1937 Lincoln Berline
26    S18_1367   1936 Mercedes-Benz 500K Special Roadster
27    S18_2795                     1928 Mercedes-Benz SSK
28    S24_2022  1938 Cadillac V-16 Presidential Limousine

In [ ]:
q = """
SELECT p.productName, p.productCode
FROM products p
JOIN orderdetails od ON p.productCode = od.productCode
JOIN orders o ON od.orderNumber = o.orderNumber
JOIN customers c ON o.customerNumber = c.customerNumber
WHERE c.customerName = 'Herkku Gifts'
"""

pd.read_sql(q, con)

   productCode                                productName
0     S12_1099                          1968 Ford Mustang
1     S12_3380                         1968 Dodge Charger
2     S12_3990                    1970 Plymouth Hemi Cuda
3     S12_4675                         1969 Dodge Charger
4     S18_1129                            1993 Mazda RX-7
5     S18_1589                      1965 Aston Martin DB5
6     S18_1889                1948 Porsche 356-A Roadster
7     S18_1984                           1995 Honda Civic
8     S18_2870               1999 Indy 500 Monte Carlo SS
9     S18_3232                1992 Ferrari 360 Spider red
10    S18_3278                       1969 Dodge Super Bee
11    S18_3482                      1976 Ford Gran Torino
12    S18_3685             1948 Porsche Type 356 Roadster
13    S24_1628                  1966 Shelby Cobra 427 S/C
14    S24_2972                    1982 Lamborghini Diablo
15    S24_3371                  1971 Alpine Renault 1600s
16    S24_3856                    1956 Porsche 356A Coupe
17    S10_1678      1969 Harley Davidson Ultimate Chopper
18    S10_2016                      1996 Moto Guzzi 1100i
19    S10_4698       2003 Harley-Davidson Eagle Drag Bike
20    S18_2625        1936 Harley Davidson El Knucklehead
21    S24_1578                          1997 BMW R 1100 S
22    S24_2000                   1960 BSA Gold Star DBD34
23    S32_1374                           1997 BMW F650 ST
24   S700_2834                              ATA: B757-300
25    S18_1342                       1937 Lincoln Berline
26    S18_1367   1936 Mercedes-Benz 500K Special Roadster
27    S18_2795                     1928 Mercedes-Benz SSK
28    S24_2022  1938 Cadillac V-16 Presidential Limousine

5. Who are the employees in Boston?

In [9]:
q="""
SELECT e.employeeNumber, e.officeCode, e.firstName, e.lastname
FROM employees e
INNER JOIN offices of ON e.officeCode=of.officeCode
WHERE of.city="Boston"
"""
pd.read_sql(q,con)

   employeeNumber  officeCode firstName   lastName
0            1188           2     Julie   Firrelli
1            1216           2     Steve  Patterson

In [ ]:
q = """
SELECT employeeNumber, firstName, lastName
FROM employees
WHERE officeCode IN (SELECT officeCode FROM offices WHERE city = 'Boston')
"""

pd.read_sql(q, con)

   employeeNumber firstName   lastName
0            1188     Julie   Firrelli
1            1216     Steve  Patterson

6. Compute the revenue generated by each sales representative based on the orders from the customers they serve.

In [ ]:
q="""
SELECT e.employeeNumber,e.firstName,e.lastName, SUM(od.quantityOrdered*od.priceEach)ASrev_generated
FROM employees e
JOIN customers c ON e.employeeNumber=c.salesRepEmployeeNumber
JOIN orders o ON c.customerNumber=o.customerNumber
JOIN orderdetails od ON orderNumber=o.orderNumber
GROUP BY e.employeeNumber,e.firstNumber, e.lastName"""
pd.read_sql(q,con)

NameError: name 'pd' is not defined

In [ ]:
q = """
SELECT e.employeeNumber, e.firstName, e.lastName, SUM(od.quantityOrdered * od.priceEach) AS revenue
FROM employees e
JOIN customers c ON e.employeeNumber = c.salesRepEmployeeNumber
JOIN orders o ON c.customerNumber = o.customerNumber
JOIN orderdetails od ON o.orderNumber = od.orderNumber
GROUP BY e.employeeNumber, e.firstName, e.lastName
"""

pd.read_sql(q, con)

    employeeNumber firstName   lastName     revenue
0             1165    Leslie   Jennings  1081530.54
1             1166    Leslie   Thompson   347533.03
2             1188     Julie   Firrelli   386663.20
3             1216     Steve  Patterson   505875.42
4             1286  Foon Yue      Tseng   488212.67
5             1323    George     Vanauf   669377.05
6             1337      Loui     Bondur   569485.75
7             1370    Gerard  Hernandez  1258577.81
8             1401    Pamela   Castillo   868220.55
9             1501     Larry       Bott   732096.79
10            1504     Barry      Jones   704853.91
11            1611      Andy     Fixter   562582.59
12            1612     Peter      Marsh   584593.76
13            1621      Mami      Nishi   457110.07
14            1702    Martin     Gerard   387477.47

7. Find the products sold in 2003 but not in 2004.

In [15]:
q="""
WITH first AS(
    SELECT p.productName, o.orderDate, p.productCode
    FROM products p
    LEFT JOIN orderdetails od ON od.productCode=p.productCode
    LEFT JOIN orders o ON o.orderNumber=od.orderNumber
    WHERE strftime("%Y",o.orderDate)="2003"
    GROUP BY p.productName),

    second AS(
      SELECT p.productName, o.orderDate, p.productCode
    FROM products p
    LEFT JOIN orderdetails od ON od.productCode=p.productCode
    LEFT JOIN orders o ON o.orderNumber=od.orderNumber
    WHERE strftime("%Y",o.orderDate)="2004"
    GROUP BY p.productName
    )
SELECT *
FROM first
LEFT JOIN second ON first.productName=second.productName
WHERE second.productName IS NULL"""
pd.read_sql(q,con)

Empty DataFrame
Columns: [productName, orderDate, productCode, productName, orderDate, productCode]
Index: []

In [17]:
q = """
WITH i AS (
SELECT p.productName, strftime('%Y', o.orderDate) year
FROM products p
LEFT JOIN orderDetails od ON od.productCode = p.productCode
LEFT JOIN orders o ON o.orderNumber = od.orderNumber
WHERE year = '2003'
GROUP BY p.productName
),

n AS (
SELECT p.productName, strftime('%Y', o.orderDate) year
FROM products p
LEFT JOIN orderDetails od ON od.productCode = p.productCode
LEFT JOIN orders o ON o.orderNumber = od.orderNumber
WHERE year = '2004'
GROUP BY p.productName
)

SELECT *
FROM i
LEFT JOIN n ON i.productName = n.productName
WHERE n.productName IS NULL
"""

pd.read_sql(q, con)

Empty DataFrame
Columns: [productName, year, productName, year]
Index: []